# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', url: 'about'}
- {name: 'Projects',  url: 'projects'}
- {name: 'Graphic Design',  url: 'graphic-design'}
- {name: 'Photography', url: 'photography'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'phone', phone:    '0428508807'}
- {icon: 'linkedin', link:   'https://www.linkedin.com/in/sabrina-menezes1/'}
- {icon: 'envelope', link:   'mailto:sabrinamenezes.design@gmail.com'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
